import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  main: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFF',
    color: '#313131',
  },
  calculadora: {
    flex: 1,
    backgroundColor: '#C5CAE9',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    alignContent: 'space-around',
  },
  tela: {
    width: '90%',
    height: '40%',
    backgroundColor: '#A5D6A7',
    borderWidth: 10,
    borderColor: 'rgba(159, 168, 218,0.8)',
    borderRadius: 0.1,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  valores: {
    width: '95%',
    height: '48%',
    textAlign: 'right',
    fontSize: 45,
  },
  resultado: {
    width: '95%',
    height: '48%',
    textAlign: 'right',
    fontSize: 45,
    color: 'rgba(0,0,0,0.25)',
  },
  teclasNumericas: {
    width: '50%',
    height: '40%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    alignContent: 'space-around',
  },
  teclasOperacoes: {
    width: '40%',
    height: '40%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    alignContent: 'space-around',
  },
  btNumero: {
    width: 50,
    height: 50,
    backgroundColor: 'rgba(159, 168, 218,1)',
    borderWidth: 3,
    borderColor: 'rgba(121, 134, 203,1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2.62,
    elevation: 5,
  },
  btZero: {
    width: 120,
    height: 50,
    backgroundColor: 'rgba(159, 168, 218,1)',
    borderWidth: 3,
    borderColor: 'rgba(121, 134, 203,1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2.62,
    elevation: 5,
  },
  btIgual: {
    width: 130,
    height: 50,
    backgroundColor: 'rgba(121, 134, 203,1)',
    borderWidth: 3,
    borderColor: 'rgba(93, 103, 160,1)',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2.62,
    elevation: 5,
  },
  btApagar: {
    width: 50,
    height: 50,
    borderWidth: 3,
    borderColor: '#d32f2f',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 2.62,
    elevation: 5,
    backgroundColor: '#ef5350',
  },
  titleBt: {
    color: '#444b73',
    fontSize: 18,
  },
});
